# Generated by Django 6.0.6 on 2026-06-29 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('padrao', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('pausada', 'Pausada')], default='planejada', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='construction.categoria')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='construction.obra')),
            ],
            options={
                'verbose_name_plural': 'operações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
